name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install PHP deps
        uses: ramsey/composer-install@v2
        
      - name: Install Box
        run: wget -O box "https://github.com/box-project/box/releases/download/4.6.1/box.phar"
        
      - name: Build
        run: bash build.sh
        
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/phpup
